### ISSUE TITLE
Does fast-crc32c actually used somewhere?

### ISSUE THREAD

**Issue by SkeLLLa** [verdaccio/verdaccio-google-cloud#16]
Does fast-crc32c actually used somewhere? Project search didn't show anything except presence in package.json. And only what I can see that this plugin does is producing a mess in console during install due to its dependency deprecations.

Also even if it used somewhere it adds only 3 times speedup. But it's not too much if we count private registry publishes. Maybe it will be valueble for some big companies that publish hundred packages per second, but for others it just adds complexity with compiling it with node-gyp.

**Comment by DanielRuf** [comment]
Hi @SkeLLLa,

So you mean that there is an unused package?

**Comment by SkeLLLa** [comment]
Looks like. And it's binary package dependency that cause some troubles.

**Comment by DanielRuf** [comment]
Yes, it is used for the defaultvalidation, see https://github.com/verdaccio/verdaccio-google-cloud/search?utf8=%E2%9C%93&q=crc32c&type=

**Comment by DanielRuf** [comment]
Which exact issues did you face?

**Comment by SkeLLLa** [comment]
@DanielRuf according to fast-crc32c docs it should used via require:
https://github.com/ashi009/node-fast-crc32c#usage

**Comment by DanielRuf** [comment]
> That pretty easy. It fails to compile from sources when you're doing npm i.

Please provide the error that you are facing. From the terminal output or logfile of npm / yarn.

**Comment by DanielRuf** [comment]
See https://github.com/googleapis/nodejs-storage/search?utf8=%E2%9C%93&q=fast-crc32c&type= for the details about the usage by `@google-cloud/storage`.

**Comment by SkeLLLa** [comment]
There are too much logs up there, but I think it's easy to reproduce using node 12. Here's the end of logs:
```
make: *** [sse4_crc32.target.mk:111: Release/obj.target/sse4_crc32/src/crc32c.o] Error 1
make: Leaving directory '/home/user/.nvm/versions/node/v12.1.0/lib/node_modules/fast-crc32c/node_modules/sse4_crc32/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/user/.nvm/versions/node/v12.1.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:196:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:256:12)
gyp ERR! System Linux 5.1.0-pf3
```

Also it produces deprecation warnings:
```
npm WARN deprecated mixin-deep@1.3.1: Critical bug fixed in v2.0.1, please upgrade to the latest version.
npm WARN deprecated set-value@2.0.0: Critical bug fixed in v3.0.1, please upgrade to the latest version.
npm WARN deprecated set-value@0.4.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.
```

Also on node 10 it produces deprecation warning during compilation as well:

```
In file included from ../src/crc32c.cpp:18:
../node_modules/nan/nan.h: In function 'void Nan::AsyncQueueWorker(Nan::AsyncWorker*)':
../node_modules/nan/nan.h:2200:62: warning: cast between incompatible function types from 'void (*)(uv_work_t*)' {aka 'void (*)(uv_work_s*)'} to 'uv_after_work_cb' {aka 'void (*)(uv_work_s*, int)'} [-Wcast-function-type]
     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
                                                              ^
../src/crc32c.cpp: In function 'Nan::NAN_METHOD_RETURN_TYPE calculateCrc(Nan::NAN_METHOD_ARGS_TYPE)':
../src/crc32c.cpp:203:40: warning: 'uint32_t v8::Value::Uint32Value() const' is deprecated: Use maybe version [-Wdeprecated-declarations]
         initCrc = info[2]->Uint32Value();
                                        ^
In file included from /opt/verdaccio/.node-gyp/10.15.3/include/node/v8.h:26,
                 from /opt/verdaccio/.node-gyp/10.15.3/include/node/node.h:63,
                 from ../node_modules/nan/nan.h:52,
                 from ../src/crc32c.cpp:18:
/opt/verdaccio/.node-gyp/10.15.3/include/node/v8.h:2477:47: note: declared here
   V8_DEPRECATED("Use maybe version", uint32_t Uint32Value() const);
                                               ^~~~~~~~~~~
/opt/verdaccio/.node-gyp/10.15.3/include/node/v8config.h:324:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/crc32c.cpp:210:47: warning: 'v8::Local<v8::Object> v8::Value::ToObject() const' is deprecated: Use maybe version [-Wdeprecated-declarations]
         Local<Object> buf = info[1]->ToObject();
                                               ^
In file included from /opt/verdaccio/.node-gyp/10.15.3/include/node/node.h:63,
                 from ../node_modules/nan/nan.h:52,
                 from ../src/crc32c.cpp:18:
/opt/verdaccio/.node-gyp/10.15.3/include/node/v8.h:10046:15: note: declared here
 Local<Object> Value::ToObject() const {
               ^~~~~
In file included from ../node_modules/nan/nan.h:52,
                 from ../src/crc32c.cpp:18:
../src/crc32c.cpp: At global scope:
/opt/verdaccio/.node-gyp/10.15.3/include/node/node.h:570:43: warning: cast between incompatible function types from 'void (*)(v8::Local<v8::Object>)' to 'node::addon_register_func' {aka 'void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)'} [-Wcast-function-type]
       (node::addon_register_func) (regfunc),                          \
                                           ^
/opt/verdaccio/.node-gyp/10.15.3/include/node/node.h:604:3: note: in expansion of macro 'NODE_MODULE_X'
   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
   ^~~~~~~~~~~~~
../src/crc32c.cpp:247:1: note: in expansion of macro 'NODE_MODULE'
 NODE_MODULE(sse4_crc32, init)
 ^~~~~~~~~~~
In file included from /opt/verdaccio/.node-gyp/10.15.3/include/node/node.h:63,
                 from ../node_modules/nan/nan.h:52,
                 from ../src/crc32c.cpp:18:
/opt/verdaccio/.node-gyp/10.15.3/include/node/v8.h: In instantiation of 'void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)]':
/opt/verdaccio/.node-gyp/10.15.3/include/node/node_object_wrap.h:85:78:   required from here
/opt/verdaccio/.node-gyp/10.15.3/include/node/v8.h:9502:16: warning: cast between incompatible function types from 'v8::WeakCallbackInfo<node::ObjectWrap>::Callback' {aka 'void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)'} to 'Callback' {aka 'void (*)(const v8::WeakCallbackInfo<void>&)'} [-Wcast-function-type]
                reinterpret_cast<Callback>(callback), type);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/verdaccio/.node-gyp/10.15.3/include/node/v8.h: In instantiation of 'void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)]':
../node_modules/nan/nan_object_wrap.h:66:61:   required from here
/opt/verdaccio/.node-gyp/10.15.3/include/node/v8.h:9502:16: warning: cast between incompatible function types from 'v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback' {aka 'void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)'} to 'Callback' {aka 'void (*)(const v8::WeakCallbackInfo<void>&)'} [-Wcast-function-type]
```

@DanielRuf yes I saw and in such usecase it should be definitely a peer-dependency of cloud-storage plugin, but not main dependency.

**Comment by DanielRuf** [comment]
Warnings can be safely ignored.
The actual error is a few lines above. Often `python2` is not defined in `PATH`. The last lines do not help us to solve your issue.

**Comment by SkeLLLa** [comment]
In my case python2 is defined. The error related to things that were deprecated in node 10 and removed in node 12.

**Comment by DanielRuf** [comment]
> Cause actual benefit from using this lib could count in milliseconds. But in order to build that library from scratch it takes much more time.

The build step is a onetime action. Well, this is how node-gyp is supposed to work. It takes time to compile C++ code against new Node headers for your platform.

There were probably good reasons to add it as normal dependency as this can prevent content musmatch errors and other issues like it is described in the storage repository of Google.

**Comment by DanielRuf** [comment]
> The error related to things that were deprecated in node 10 and removed in node 12.

Still, we need the actual error / more lines. Warnings are not errors.

**Comment by SkeLLLa** [comment]
> There were probably good reasons to add it as normal dependency as this can prevent content musmatch errors and other issues like it is described in the storage repository of Google.

No. It just used as "faster" replacement of native js crc32c implementation and google storage works without it.

**Comment by DanielRuf** [comment]
The issue comes from sse4-crc32.

See https://github.com/anandsuresh/sse4_crc32/issues/74

Try downgrading to 10 KTS (12 is stable, not LTS) or try `npm install --no-optional`.

We will check the fast-crc32c dependency to see if we can remove it.

**Comment by DanielRuf** [comment]
The issue comes from sse4-crc32.

See https://github.com/anandsuresh/sse4_crc32/issues/74

Try downgrading to 10 LTS (12 is stable, not LTS) or try `npm install --no-optional`.

We will check the fast-crc32c dependency to see if we can remove it.

**Comment by juanpicado** [comment]
It seems this dependency is needed whether `resumsable` on upload files is enabled.

```
* You can specify whether or not an upload is resumable by setting
   * `options.resumable`. *Resumable uploads are enabled by default if your
   * input file is larger than 5 MB.*
   *
   * For faster crc32c computation, you must manually install
   * [`fast-crc32c`](http://www.gitnpm.com/fast-crc32c):
   *
   *     $ npm install --save fast-crc32c
   *
```

https://github.com/googleapis/nodejs-storage/blob/788113ac6c0922ba458fcef729d2d93f340a0381/src/bucket.ts#L2927

**Comment by DanielRuf** [comment]
> It seems this dependency is needed whether resumsable on upload files is enabled.

Not really as it is only a "faster" replacement. According to @SkeLLLa it also should work without it.

**Comment by SkeLLLa** [comment]
@juanpicado It uses here:
https://github.com/stephenplusplus/hash-stream-validation/blob/46449b8c8a361a5eb6a40be4496832a1a242227f/index.js#L5

And if there's no such lib it will use standard one.

**Comment by juanpicado** [comment]
Then :) we have only one option. PR. But I would go with a feat:() instead

**Comment by juanpicado** [comment]
What if we ... 
```
"optionalDependencies": {
    "fast-crc32c": "1.0.4"
  },
``` 
?

**Comment by DanielRuf** [comment]
> optionalDependencies

This is already the case. `--no-optional` would probably solve it afaik.

**Comment by DanielRuf** [comment]
The native dependency which throws the error is already an optional deoendency afaik. Not sure if `--no-optional` would already solve that. But we can also move it in our root package.json to the optional dependencies.

**Comment by juanpicado** [comment]
I think it is not, I haven't found any reference in their source code.
https://cloud.google.com/nodejs/docs/reference/storage/1.7.x/File

![Screen Shot 2019-06-30 at 8 00 57 AM](https://user-images.githubusercontent.com/558752/60392945-4110a200-9b0d-11e9-8030-2c2876db883d.png)

So, I think we have answer the question. I think a future PR might either remove it or add it as optionalDepedency, but I'd rather remove it and update the README file since there is nothing to add in this plugin, the google npm dependency will detect that automatically.

**Comment by DanielRuf** [comment]
See https://github.com/verdaccio/verdaccio-google-cloud/issues/16#issuecomment-504013163 ;-)

**Comment by juanpicado** [comment]
Ahh, sorry my bad @DanielRuf  I did not read that part 👍 thanks for the clarification 😊
