### ISSUE TITLE
Duplicate packages when publishing

### ISSUE THREAD

**Issue by MichielDeMey** [verdaccio/verdaccio-google-cloud#6]
Hi!

Not sure if it's specifically for this plugin but we've noticed duplicate packages when publishing to our NPM registry using this plugin.

![screen shot 2018-08-06 at 13 22 35](https://user-images.githubusercontent.com/793406/43714066-16d105cc-997c-11e8-8337-795339596d72.png)

In Google DataStore we can also see duplicate names.

![screen shot 2018-08-06 at 13 24 50](https://user-images.githubusercontent.com/793406/43714102-31a325f6-997c-11e8-9874-8513f82ceb30.png)

Not much output is shown other than 2 POST requests.

![screen shot 2018-08-06 at 13 29 28](https://user-images.githubusercontent.com/793406/43714362-09766dee-997d-11e8-970d-dea5cee691ca.png)

Currently using `yarn` to publish packages.

**Comment by juanpicado** [comment]
It might be, still experimental. I haven't had enough time to test it deeply.

**Comment by serratedserenade** [comment]
Getting this issue as well, I'd love to work on this but I don't know where to begin

**Comment by juanpicado** [comment]
Hi @serratedserenade , I'd start reviewing the unit tests. I think the issue is within this plugin. Let me know if you need help.

**Comment by juanpicado** [comment]
I think the problem might be, the way I'm checking whether some entity exist is not well developed

**Comment by serratedserenade** [comment]
Yeah I saw, I'm just randomly brute forcing the issue here haha, I do notice `add` is called without checking if the package exists yet so I think that's maybe it (?). I'm not 100% familiar with the working of the storage plugin or how verdaccio works internally yet.

**Comment by serratedserenade** [comment]
My attempt at the fix #8

**Comment by juanpicado** [comment]
Have you tried already this fix on live? @serratedserenade

**Comment by serratedserenade** [comment]
Yeah, tested it with our own Google Cloud project, the duplication no longer occurs on the following cases:

* Unpublishing a version and republishing it
* Publishing a new version

**Comment by juanpicado** [comment]
published on `verdaccio-google-cloud@0.0.9`

**Comment by MichielDeMey** [comment]
Just tested this and confirmed working using `verdaccio-google-cloud@0.0.9`. 👍

**Comment by juanpicado** [comment]
Thanks for you help :)
